# Pipe separate tests into ctest
# Adapted from https://github.com/elbeno/skeleton/blob/master/CMakeLists.txt
macro(ADD_INDIVIDUAL_TESTS executable type suffix)
  set(test_path $ENV{PATH})
  get_target_property(target_files ${executable} SOURCES)
  foreach(source ${target_files})
    string(REGEX MATCH .*cpp source "${source}")
    if(source)
      file(READ "${source}" contents)
      string(REGEX MATCHALL "DEF_${type}[ ]*[(][ ]*[^, ]+[ ]*,[ ]*[^,) ]+[ ]*[),]" found_tests ${contents})
      foreach(hit ${found_tests})
        string(REGEX REPLACE "DEF_${type}[ ]*[(][ ]*([^, ]+)[ ]*,[ ]*[^,) ]+[ ]*[),]" "\\1" tname ${hit})
        string(REGEX REPLACE "DEF_${type}[ ]*[(][ ]*[^, ]+[ ]*,[ ]*([^,) ]+)[ ]*[),]" "\\1" sname ${hit})
        set(test_name ${executable}.${sname}.${tname}${suffix})
        add_test(NAME ${test_name}
          COMMAND "${executable}" --testName=${tname}${suffix} --suiteName=${sname})
        set_tests_properties(${test_name} PROPERTIES TIMEOUT 30 ENVIRONMENT "PATH=${test_path}")
      endforeach()
    endif()
  endforeach()
endmacro()

macro(ADD_TESTINATOR_TESTS executable)
  ADD_INDIVIDUAL_TESTS(${executable} "TEST" "")
  ADD_INDIVIDUAL_TESTS(${executable} "TIMED_TEST" "")
  ADD_INDIVIDUAL_TESTS(${executable} "PROPERTY" "Property")
  ADD_INDIVIDUAL_TESTS(${executable} "COMPLEXITY_PROPERTY" "ComplexityProperty")
endmacro()